### ISSUE TITLE
DigiCert may have changed naming convention which makes import Script Fail

### ISSUE THREAD

**Issue by CallanTurner** [MicrosoftLearning/MS-721T00-Collaboration-Communications-Systems-Engineer#30]
# Module: 00
#### Step: 3

Description of issue
DigiCert may have changed naming convention which makes import Script Fail

![image](https://github.com/MicrosoftLearning/MS-721T00-Collaboration-Communications-Systems-Engineer/assets/42951775/edb18d88-1af0-435e-a8b9-10293ef6cb5a)

**Comment by SkillableBB** [comment]
Confirming this on Skillable's end; moving the file into Downloads or Labfiles folders makes no difference: 


![image](https://github.com/MicrosoftLearning/MS-721T00-Collaboration-Communications-Systems-Engineer/assets/94069201/02a6c0f6-cc4f-4065-b456-59797fd03edc)

**Comment by dahans-msft2** [comment]
Thanks for reporting this @CallanTurner  and @SkillableBB.  I just tested and was unable to reproduce the issue.  

I suspect that when downloading the ZIP file from the Digicert email, the file was saved as "certs.zip" instead of the default name, which should be sbc01_labNNNNN_o365ready...zip, as in this screenshot:

![image](https://github.com/MicrosoftLearning/MS-721T00-Collaboration-Communications-Systems-Engineer/assets/49003767/05ee3bd3-48b6-496f-a457-f76f57981025)

I tested a brand new lab instance and received the email from Digicert with the correctly named ZIP. Downloading it as-is to the Downloads folder allows for the tool to import the certificate successfully.

Can you confirm whether you renamed the zip file as you downloaded it, or did the ZIP file you receive from Digicert contain the incorrectly named ZIP file?

Thanks!

**Comment by CallanTurner** [comment]
There were 8 participants that all had the same issue. We did not change the name of the zip file. It downloaded as cert.zip. We did try renaming the downloaded file and moving it to the scripts folder. This did not solve the issue.

Regards,


Callan Turner
Technical Instructor Microsoft
Lumify Group - Melbourne

Callan Turner
Technical Instructor
Microsoft, Cisco, Domino
+61 3 9675 5214
***@***.***
www.lumifywork.com
Level 12A, 45 William Street,Melbourne, VIC 3000
DDLS Australia Pty Ltd, Trading as Lumify Work accepts no liability for the content of this email, or for the consequences of any actions taken on the basis of the information provided, unless that information is subsequently confirmed in writing. Any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company.
________________________________

**Comment by dahans-msft2** [comment]
Hi Callan, glad that it's resolved as of now.  We're engaging with Digicert to see if there was an outage or root cause for the behavior we saw. I'm unsure why renaming the ZIP file didn't work, but I know it's looking for a specific filename format and it might be tricky to get it exactly right.  If this keeps happening, we'll add a workaround to the instructions so students can proceed next time.  Thanks for bringing this to our attention, I really appreciate it.

**Comment by CallanTurner** [comment]
Thanks Darrin.

Regards


Callan
________________________________
